name: Build Docker Image

on:
  pull_request:
#  push:
#    branches:
#      - master
#  release:
#    types:
#      - published

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag name
        id: image_tag_name
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Debug credentials
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          - echo "foo"
          - echo $REPO_OWNER
          - echo "bar"

      - name: Login to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/smartassert/compiler:${{ steps.image_tag_name.outputs.value }}
